version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chat-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatdb
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: chat-api
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/chatdb?sslmode=disable

volumes:
  pgdata:
